### ISSUE TITLE
Navigation between view model to view model not working

### ISSUE THREAD

**Issue by Codeadmire** [Bowman74/fmvvm#23]
I am getting the following error when give navigation from login page to dashboard page:

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'findAncestorStateOfType' was called on null.
Receiver: null
Tried calling: findAncestorStateOfType<NavigatorState>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Navigator.of (package:flutter/src/widgets/navigator.dart:2115:19)
#2      FmvvmNavigationService.navigate (package:fmvvm/fmvvmnavigationservice.dart:17:21)
#3      LoginViewModel.loginCommand.<anonymous closure> (package:fmvvmexploreapp/src/viewmodels/LoginPageViewModel.dart:27:20)
#4      LoginViewState.build.<anonymous closure> (package:fmvvmexploreapp/src/views/LoginPageView.dart:131:58)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer.handleTapUp (package:flu<…>

**Comment by Codeadmire** [comment]
[[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'findAncestorStateOfType' was called on null.
Receiver: null
Tried calling: findAncestorStateOfType<NavigatorState>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Navigator.of (package:flutter/src/widgets/navigator.dart:2115:19)
#2      FmvvmNavigationService.navigate (package:fmvvm/fmvvmnavigationservice.dart:17:21)
#3      LoginViewModel.loginCommand.<anonymous closure> (package:fmvvmexploreapp/src/viewmodels/LoginPageViewModel.dart:27:20)
#4      LoginViewState.build.<anonymous closure> (package:fmvvmexploreapp/src/views/LoginPageView.dart:131:58)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer.handleTapUp (package:flu<…>](url)
